services:
  localstack:
    image: localstack/localstack:3.8
    container_name: tc5-mimir-localstack
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4568:4566"
    volumes:
      - ./localstack/init:/etc/localstack/init/ready.d

  mimir:
    build:
      context: .
    container_name: tc5-mimir
    environment:
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
      - REPORT_REQUEST_QUEUE_URL=http://localstack:4566/000000000000/requested-report
      - ANALYSIS_TABLE_NAME=analises-arquitetura
      - REPORTS_BUCKET_NAME=techchallenge-fase5-reports
      - REPORTS_PREFIX=reports
      - POLL_WAIT_SECONDS=3
      - MAX_MESSAGES=1
    depends_on:
      - localstack
